# Generated by Django 4.2 on 2026-01-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=20),
        ),
    ]
